### ISSUE TITLE
'vagrant destroy' always executes 'config.trigger.after'

### ISSUE THREAD

**Issue by jeff1evesque** [emyl/vagrant-triggers#61] opened 2016-02-25 18:31 UTC
On the last minute, I decided I didn't want to `vagrant destroy`:

```bash
$ vagrant destroy
    default: Are you sure you want to destroy the 'default' VM? [y/N] n
==> default: The VM 'default' will not be destroyed, since the confirmation
==> default: was declined.
==> default: Running triggers after destroy...
==> default: Executing command "rm -Rf log"...
==> default: Command execution finished.
==> default: Executing command "rm -Rf puppet/environment/development/modules_contrib"...
==> default: Command execution finished.
==> default: Executing command "rm -Rf webroot/sites/all/themes/custom/drupal-demonstration/asset"...
==> default: Command execution finished.
==> default: Executing command "rm -Rf webroot/sites/default/files/!(README.md)"
...
==> default: Command execution finished.
==> default: Executing command "rm -f webroot/sites/default/settings.php"...
==> default: Command execution finished.
==> default: Executing command "rm -f src/default/settings.php"...
==> default: Command execution finished.
```

Instead, I wanted to reprovision, hoping it would save time.  However, it seems to have executed `config.trigger.after :destroy`, regardless:

```bash
$ vagrant provision
There are errors in the configuration of this machine. Please fix
the following errors and try again:

puppet provisioner:
* The configured module path doesn't exist: /path/to/drupal-demonstration/puppet/environment/development/modules_contrib
* The configured module path doesn't exist: /path/to/drupal-demonstration/puppet/environment/development/modules_contrib
* The configured module path doesn't exist: /path/to/drupal-demonstration/puppet/environment/development/modules_contrib
* The configured module path doesn't exist: /path/to/drupal-demonstration/puppet/environment/development/modules_contrib
* The configured module path doesn't exist: /path/to/drupal-demonstration/puppet/environment/development/modules_contrib
* The configured module path doesn't exist: /path/to/drupal-demonstration/puppet/environment/development/modules_contrib
* The configured module path doesn't exist: /path/to/drupal-demonstration/puppet/environment/development/modules_contrib
```

So, I was stuck to officially `vagrant destroy`, before `vagrant up`.

**Comment by SchulteMarkus** [comment] 2016-03-10 07:34
This problem is similar for 

    config.trigger.before :destroy

Which is executed (in any case) before "Are you sure you want to destroy the 'default' VM?"

**Comment by emyl** [comment] 2016-03-20 18:54
Duplicate of #40

**Closed by emyl** 2016-03-20 18:54 UTC
